FROM openjdk

VOLUME /tmp
ADD maven/ratings-summary-${docker.image.version}.jar myapp.jar
RUN sh -c 'touch /myapp.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/myapp.jar"]
